profile: 'sample'
initial_wts: {}
models: []
feeds:
- id: 0
  name: "The Economist - Science and Technology"
  is_oped_blog: false
  url: "http://www.economist.com/sections/science-technology/rss.xml"
- id: 1
  name: "The Economist - Business and Finance"
  is_oped_blog: false
  url: "http://www.economist.com/sections/business-finance/rss.xml"
- id: 2
  name: "The Economist - Economics"
  is_oped_blog: false
  url: "http://www.economist.com/sections/economics/rss.xml"
- id: 3
  name: "The Economist - Culture"
  is_oped_blog: false
  url: "http://www.economist.com/sections/culture/rss.xml"
- id: 4
  name: "The Economist - US Politics"
  is_oped_blog: false
  url: "http://www.economist.com/sections/united-states/rss.xml"
- id: 5
  name: "The Economist - International Politics"
  is_oped_blog: false
  url: "http://www.economist.com/sections/international/rss.xml"
- id: 6
  name: "The Economist - Britain Politics"
  is_oped_blog: false
  url: "http://www.economist.com/sections/britain/rss.xml"
- id: 7
  name: "Associated Press - Top Headlines"
  is_oped_blog: false
  url: "http://hosted2.ap.org/atom/APDEFAULT/3d281c11a96b4ad082fe88aa0db04305"
- id: 8
  name: "Associated Press - US National"
  url: "http://hosted2.ap.org/atom/APDEFAULT/386c25518f464186bf7a2ac026580ce7"
  is_oped_blog: false
- id: 9
  name: "Associated Press - World"
  url: "http://hosted2.ap.org/atom/APDEFAULT/cae69a7523db45408eeb2b3a98c0c9c5"
  is_oped_blog: false
- id: 10
  name: "Associated Press - Politics"
  url: "http://hosted2.ap.org/atom/APDEFAULT/89ae8247abe8493fae24405546e9a1aa"
  is_oped_blog: false
- id: 11
  name: "Associated Press - Business"
  url: "http://hosted2.ap.org/atom/APDEFAULT/f70471f764144b2fab526d39972d37b3"
  is_oped_blog: false
- id: 12
  name: "Associated Press - Technology"
  url: "http://hosted2.ap.org/atom/APDEFAULT/495d344a0d10421e9baa8ee77029cfbd"
  is_oped_blog: false
- id: 13
  name: "Associated Press - Sports"
  url: "http://hosted2.ap.org/atom/APDEFAULT/347875155d53465d95cec892aeb06419"
  is_oped_blog: false
- id: 14
  name: "Associated Press - Entertainment"
  url: "http://hosted2.ap.org/atom/APDEFAULT/4e67281c3f754d0696fbfdee0f3f1469"
  is_oped_blog: false
- id: 15
  name: "Associated Press - Health"
  url: "http://hosted2.ap.org/atom/APDEFAULT/bbd825583c8542898e6fa7d440b9febc"
  is_oped_blog: false
- id: 16
  name: "Associated Press - Science"
  url: "http://hosted2.ap.org/atom/APDEFAULT/b2f0ca3a594644ee9e50a8ec4ce2d6de"
  is_oped_blog: false
- id: 17
  name: "Associated Press - Strange"
  url: "http://hosted2.ap.org/atom/APDEFAULT/aa9398e6757a46fa93ed5dea7bd3729e"
  is_oped_blog: false
- id: 18
  name: "Wired - Top Stories"
  is_oped_blog: false
  url: "https://www.wired.com/feed/rss"
- id: 19
  name: "Wired - Business"
  is_oped_blog: false
  url: "https://www.wired.com/feed/category/business/latest/rss"
- id: 20
  name: "Wired - Culture"
  is_oped_blog: false
  url: "https://www.wired.com/feed/category/culture/latest/rss"
- id: 21
  name: "Wired - Gears"
  is_oped_blog: false
  url: "https://www.wired.com/feed/category/gear/latest/rss"
- id: 22
  name: "Wired - Science"
  is_oped_blog: false
  url: "https://www.wired.com/feed/category/science/latest/rss"
- id: 23
  name: "Wired - Security"
  is_oped_blog: false
  url: "https://www.wired.com/feed/category/security/latest/rss"
- id: 24
  name: "Wired - Transportation"
  is_oped_blog: false
  url: "https://www.wired.com/feed/category/transportation/latest/rss"
- id: 25
  name: "TechCrunch - News"
  is_oped_blog: false
  url: "http://feeds.feedburner.com/TechCrunch/"
  is_oped_blog: false
- id: 26
  name: "Denver Post - Breaking News"
  url: "http://feeds.denverpost.com/dp-news-breaking"
  is_oped_blog: false
- id: 27
  name: "Denver Post - Top Stories"
  url: "http://feeds.denverpost.com/dp-news-topstories"
  is_oped_blog: false
- id: 28
  name: "Denver Post - Business"
  url: "http://feeds.denverpost.com/dp-business"
  is_oped_blog: false
- id: 29
  name: "Pew Research Center - Latest"
  url: "http://www.pewresearch.org/feed/"
  is_oped_blog: false
- id: 30
  name: "NY Times - World - Politics"
  url: "http://rss.nytimes.com/services/xml/rss/nyt/World.xml"
  is_oped_blog: false
- id: 31
  name: "NY Times - U.S. - Politics"
  url: "http://www.nytimes.com/services/xml/rss/nyt/Politics.xml"
  is_oped_blog: false
- id: 32
  name: "NY Times - Business"
  url: "http://rss.nytimes.com/services/xml/rss/nyt/Business.xml"
  is_oped_blog: false
- id: 33
  name: "NY Times - Technology"
  url: "http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"
  is_oped_blog: false
- id: 34
  name: "NY Times - Science"
  is_oped_blog: false
  url: "http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"
- id: 35
  name: "NY Times - Health"
  is_oped_blog: false
  url: "http://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"
- id: 36
  name: "Ars Technica - All Latest"
  is_oped_blog: false
  url: "http://feeds.arstechnica.com/arstechnica/index"
- id: 37
  name: The Atlantic - Business
  is_oped_blog: false
  url: http://feeds.feedburner.com/AtlanticBusinessChannel
- id: 38
  name: Entreprenuer
  is_oped_blog: false
  url: http://feeds.feedburner.com/entrepreneur/latest
- id: 39
  name: Harvard Business Review
  url: http://feeds.harvardbusiness.org/harvardbusiness/
  is_oped_blog: false
- id: 40
  name: Freakonomics
  url: http://freakonomics.com/feed/
  is_oped_blog: true
- id: 41
  name: The Business of Fashion
  url: https://www.businessoffashion.com/syndication/feed
  is_oped_blog: false
- id: 42
  name: The Big Picture
  url: http://feeds.feedburner.com/TheBigPicture
  is_oped_blog: true
- id: 43
  name: VentureBeat
  url: http://feeds.feedburner.com/venturebeat
  is_oped_blog: false
- id: 44
  name: Business Insider
  url: http://feeds2.feedburner.com/businessinsider
  is_oped_blog: false
- id: 45
  name: Calculated Risk
  url: http://feeds.feedburner.com/CalculatedRisk
  is_oped_blog: true
- id: 46
  name: Inc.com
  url: http://feeds.inc.com/home/updates
  is_oped_blog: true
- id: 47
  name: Andrew Chen
  url: http://andrewchen.co/feed/
  is_oped_blog: true
- id: 48
  name: The Huffington Post - Small Business
  url: http://feeds.huffingtonpost.com/c/35496/f/677090/index.rss
  is_oped_blog: false
- id: 49
  name: strategy+business - All Updates
  url: http://feeds.feedburner.com/StrategyBusiness-AllUpdates
  is_oped_blog: true
- id: 50
  name: Fortune
  url: http://fortune.com/feed/
  is_oped_blog: false
- id: 51
  name: The NonProfit Times
  url: http://www.thenonprofittimes.com/feed/
  is_oped_blog: false
- id: 52
  name: Hotel Business Magazine Breaking News
  url: https://www.hotelbusiness.com/links/rss/hb_rss_01.php
  is_oped_blog: false
- id: 53
  name: Smart Business Magazine
  url: http://www.sbnonline.com/feed/
  is_oped_blog: false
- id: 54
  name: Bloomberg
  url: http://www.newslookup.com/rss/business/bloomberg.rss
  is_oped_blog: false
- id: 55
  name: DataMiningBlog.com
  url: http://feeds.feedburner.com/dataminingblog
  is_oped_blog: true
- id: 56
  name: Geeking with Greg
  url: http://feeds.feedburner.com/GeekingWithGreg
  is_oped_blog: true
- id: 57
  name: No Free Hunch
  url: http://blog.kaggle.com/feed/
  is_oped_blog: true
- id: 58
  name: KDnuggets - Data Analytics
  url: http://feeds.feedburner.com/kdnuggets-data-mining-analytics
  is_oped_blog: true
- id: 59
  name: Big Data, Plainly Spoken (aka Numbers Rule Your World)
  url: http://junkcharts.typepad.com/numbersruleyourworld/atom.xml
  is_oped_blog: true
- id: 60
  name: The Guardian - Datablog
  url: http://www.theguardian.com/news/datablog/rss
  is_oped_blog: true
- id: 61
  name: Wall Street Journal - The Numbers
  url: https://blogs.wsj.com/numbers/feed/
  is_oped_blog: true
- id: 62
  name: Simply Statistics
  url: https://simplystatistics.org/index.xml
  is_oped_blog: true
- id: 63
  name: Revolution Analytics
  url: http://blog.revolutionanalytics.com/atom.xml
  is_oped_blog: true
- id: 64
  name: R-bloggers
  url: http://feeds.feedburner.com/RBloggers
  is_oped_blog: true
- id: 65
  name: Math Babe
  url: https://mathbabe.org/feed/
  is_oped_blog: true
- id: 66
  name: Statistical Modeling, Causal Inference, and Social Science
  url: http://feeds.feedburner.com/StatisticalModeling
  is_oped_blog: true
- id: 67
  name: FiveThirtyEight
  url: http://fivethirtyeight.com/feed/
  is_oped_blog: true
- id: 68
  name: Data Science 101
  url: http://101.datascience.community/feed/
  is_oped_blog:
- id: 69
  name: Nuit Blanche
  url: http://feeds.feedburner.com/blogspot/wCeDd
  is_oped_blog:
- id: 70
  name: John D. Cook - The Endeavour
  url: http://feeds.feedburner.com/theendeavour
  is_oped_blog: true
- id: 71
  name: Machine Learning (Theory)
  url: http://hunch.net/?feed=rss2
  is_oped_blog: true
- id: 72
  name: SmartData Collective
  url: http://feeds.feedburner.com/smartdatacollective_allposts
  is_oped_blog: true
- id: 73
  name: CNN - Top Stories
  url: http://rss.cnn.com/rss/cnn_topstories.rss
  is_oped_blog: false
- id: 74
  name: NY Times - Homepage
  url: http://feeds.nytimes.com/nyt/rss/HomePage
  is_oped_blog: false
- id: 75
  name: Washington Post - Highlights
  url: http://www.washingtonpost.com/rss/
  is_oped_blog: false
- id: 76
  name: USA Today - Top Stories
  url: http://rssfeeds.usatoday.com/usatoday-NewsTopStories
  is_oped_blog: false
- id: 77
  name: NPR - News
  url: http://www.npr.org/rss/rss.php?id=1001
  is_oped_blog: false
- id: 78
  name: Reuters - Top News
  url: http://feeds.reuters.com/reuters/topNews
  is_oped_blog: false
- id: 79
  name: NY Times - Sports
  url: http://feeds1.nytimes.com/nyt/rss/Sports
  is_oped_blog: false
- id: 80
  name: Sports Illustrated
  url: http://www.si.com/rss/si_topstories.rss
  is_oped_blog: false
- id: 81
  name: NPR - Arts & Culture
  url: http://www.npr.org/rss/rss.php?id=1008
  is_oped_blog: false
- id: 82
  name: NPR - Movies
  url: http://www.npr.org/rss/rss.php?id=1045
  is_oped_blog: false
- id: 83
  name: Reuters - World News
  url: http://feeds.reuters.com/Reuters/worldNews
  is_oped_blog: false 
- id: 84
  name: CBN - World News
  url: http://www.cbn.com/cbnnews/world/feed/
  is_oped_blog: false
- id: 85 
  name: BBC - World News
  url: http://feeds.bbci.co.uk/news/world/rss.xml
  is_oped_blog: false
- id: 86
  name: Yahoo - US News
  url: http://news.yahoo.com/rss/
  is_oped_blog: false 
- id: 87 
  name: Reuters - Arts & Culture
  url: http://feeds.reuters.com/news/artsculture
  is_oped_blog: false
- id: 88
  name: Reuters - Politics
  url: http://feeds.reuters.com/Reuters/PoliticsNews
  is_oped_blog: false
- id: 89
  name: Reuters - Sports
  url: http://feeds.reuters.com/reuters/sportsNews
  is_oped_blog: false
- id: 90
  name: Reuters - Money
  url: http://feeds.reuters.com/news/wealth
  is_oped_blog: false
- id: 91
  name: Reuters - Entertainment
  url: http://feeds.reuters.com/reuters/entertainment
  is_oped_blog: false
- id: 92 
  name: Reuters - Health
  url: http://feeds.reuters.com/reuters/healthNews
  is_oped_blog: false 
- id: 93
  name: Reuters - People
  url: http://feeds.reuters.com/reuters/peopleNews
  is_oped_blog: false
- id: 94
  name: Politico - Josh Gerstein
  url: http://www.politico.com/rss/undertheradar_full.xml
  is_oped_blog: true
- id: 95
  name: Politico - Congress
  url: http://www.politico.com/rss/congress.xml
  is_oped_blog: false
- id: 96
  name: Politico - Health Care
  url: http://www.politico.com/rss/healthcare.xml
  is_oped_blog: false
- id: 97
  name: Politico - Defense
  url: http://www.politico.com/rss/defense.xml
  is_oped_blog: false
- id: 98
  name: Politico - Politics
  url: http://www.politico.com/rss/politics08.xml
  is_oped_blog: false
- id: 99
  name: CNN - World
  url: http://rss.cnn.com/rss/cnn_world.rss
  is_oped_blog: false
- id: 100
  name: CNN - Politics
  url: http://rss.cnn.com/rss/cnn_allpolitics.rss
  is_oped_blog: false
- id: 101
  name: CNN - Entertainment
  url: http://rss.cnn.com/rss/cnn_showbiz.rss
  is_oped_blog: false
- id: 102
  name: Rolling Stone - All News
  url: https://www.rollingstone.com/rss
  is_oped_blog: false
- id: 103
  name: Rolling Stone - Politics
  url: https://www.rollingstone.com/politics/rss
  is_oped_blog: ture

